markdown: kramdown
url: ''
baseurl: null
title: Oswaldo L. Zárate
description: Bienvenido a mi website personal!
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: 
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: olzarate251@gmail.com
facebook_username: osvaldo.zarate.77
twitter_username: walozarate
instagram_username: /
linkedin_username: ozarate
github_username: walozarate
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: UA-163806439-1
disqus-shortname: thedevslot
author-name: OsVeloper
author-image: >-
  https://github.com/OswaldoZarate.png
author-about: >-
  Mi nombre es Oswaldo y soy profesional independiente en modelado con Machine Learning,
  Deep Learningy Visión por computadora, además de otras habilidades.
  Mi objetivo es formar parte de un equipo de trabajo donde pueda contribuir y demostrar
  el conocimiento y las habilidades que poseo.
  Te invito cordialmente a revisar mi Portafolio de Proyectos, donde almaceno 
  aplicaciones que desarrollo; así mismo mi Blog, que contiene noticias y tutoriales; 
  también revise el Panel Curriculum Vitae, que contiene certificaciones obtenidas y 
  habilidades que poseo.
  Muchas Gracias por su visita !!! puede contactarme en mis redes sociales.
author-url: 'https://github.com/walozarate'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
